import crypto from "crypto";
import { getActiveIpaymuCredentials } from "@/lib/services/ipaymu-config-service";

function envFallback() { const production = (process.env.IPAYMU_ENV ?? "sandbox").toLowerCase() === "production"; return { environment: production ? "production" as const : "sandbox" as const, va: production ? process.env.IPAYMU_PRODUCTION_VA ?? "" : process.env.IPAYMU_SANDBOX_VA ?? "", apiKey: production ? process.env.IPAYMU_PRODUCTION_API_KEY ?? "" : process.env.IPAYMU_SANDBOX_API_KEY ?? "" }; }
async function credentials() { return (await getActiveIpaymuCredentials()) ?? envFallback(); }
export function isIpaymuActive() { return true; }
export function appUrl() { return (process.env.IPAYMU_APP_URL ?? process.env.NEXT_PUBLIC_APP_URL ?? "").replace(/\/+$/, ""); }
export async function isIpaymuConfigured() { const c = await credentials(); return isIpaymuActive() && Boolean(c.va && c.apiKey); }
function bodyHash(body: Record<string, unknown>) { return crypto.createHash("sha256").update(JSON.stringify(body)).digest("hex"); }
async function signature(method: string, body: Record<string, unknown>) { const c = await credentials(); const stringToSign = `${method}:${c.va}:${bodyHash(body)}:${c.apiKey}`; return crypto.createHmac("sha256", c.apiKey).update(stringToSign).digest("hex"); }
export async function baseUrl() { return (await credentials()).environment === "production" ? "https://my.ipaymu.com" : "https://sandbox.ipaymu.com"; }
export interface IpaymuProduct { name: string; price: number; qty: number; description?: string; imageUrl?: string }
export interface IpaymuRedirectParams { referenceId: string; amount: number; product: IpaymuProduct[]; buyerName: string; buyerEmail?: string; buyerPhone?: string; returnUrl: string; notifyUrl: string; cancelUrl: string; expired?: number }
export interface IpaymuRedirectResult { url: string; referenceId: string }
export async function createIpaymuRedirect(p: IpaymuRedirectParams): Promise<IpaymuRedirectResult> { if (!(await isIpaymuConfigured())) throw new Error("iPaymu belum dikonfigurasi"); const body: Record<string, unknown> = { product: p.product.map(x => x.name), qty: p.product.map(x => String(x.qty)), price: p.product.map(x => String(x.price)), description: p.product.map(x => x.description ?? x.name), imageUrl: p.product.map(x => x.imageUrl ?? ""), buyerName: p.buyerName, referenceId: p.referenceId, amount: p.amount, returnUrl: p.returnUrl, notifyUrl: p.notifyUrl, cancelUrl: p.cancelUrl }; if (p.buyerEmail) body.buyerEmail = p.buyerEmail; if (p.buyerPhone) body.buyerPhone = p.buyerPhone; if (p.expired) body.expired = p.expired; const res = await fetch(`${await baseUrl()}/api/v2/payment`, { method: "POST", headers: { "Content-Type": "application/json", va: (await credentials()).va, signature: await signature("POST", body), timestamp: new Date().toISOString() }, body: JSON.stringify(body) }); if (!res.ok) throw new Error(`iPaymu gagal (${res.status}): ${(await res.text()).slice(0, 300)}`); const json = await res.json() as Record<string, unknown>; const data = (json.Data ?? json.data ?? {}) as Record<string, unknown>; const url = String(data.Url ?? data.url ?? json.Url ?? json.url ?? ""); if (!url) throw new Error("iPaymu tidak mengembalikan URL"); return { url, referenceId: p.referenceId }; }
export async function verifyIpaymuCallback(body: Record<string, unknown>, received: string) { const c = await credentials(); const sorted: Record<string, unknown> = {}; Object.keys(body).sort().forEach(k => { sorted[k] = body[k]; }); const expected = crypto.createHmac("sha256", c.va).update(JSON.stringify(sorted).replace(/\//g, "\\/")).digest("hex"); const a = Buffer.from(expected); const b = Buffer.from(received); return a.length === b.length && crypto.timingSafeEqual(a, b); }
export async function verifyIpaymuCallbackHmac(body: Record<string, unknown>, signatureValue: string) { return verifyIpaymuCallback(body, signatureValue); }
export async function verifyCallback(body: Record<string, unknown>, signatureValue: string) { return verifyIpaymuCallback(body, signatureValue); }
export interface IpaymuCheckResult { referenceId: string; status: string; statusCode: number; transactionStatusCode: number; paidStatus: string; transactionId: string; amount: number; subtotal: number; paidAt: string | null }
export async function checkIpaymuTransaction(transactionId: string): Promise<IpaymuCheckResult> { const c = await credentials(); const body = { transactionId }; const res = await fetch(`${await baseUrl()}/api/v2/transaction`, { method: "POST", headers: { "Content-Type": "application/json", va: c.va, signature: await signature("POST", body), timestamp: new Date().toISOString() }, body: JSON.stringify(body) }); if (!res.ok) throw new Error(`iPaymu check gagal (${res.status})`); const json = await res.json() as Record<string, unknown>; const data = (json.Data ?? json.data ?? json) as Record<string, unknown>; return { referenceId: String(data.reference_id ?? data.referenceId ?? ""), status: String(data.status ?? "unknown"), statusCode: Number(data.status_code ?? -99), transactionStatusCode: Number(data.transaction_status_code ?? -99), paidStatus: String(data.paid_status ?? ""), transactionId: String(data.trx_id ?? transactionId), amount: Number(data.sub_total ?? data.amount ?? 0), subtotal: Number(data.sub_total ?? 0), paidAt: typeof data.paid_at === "string" ? data.paid_at : null }; }
